name: Tyler Fritz
email: tyofritz@gmail.com
github_username: tofritz

title: a personal website
description: >-
  a place to document my thoughts, projects, and interests.
baseurl: ""
url: ""

permalink: /:year/:month/:day/:title

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions:
    ["strikethrough", "autolink", "tasklist", "autolink", "table", "tagfilter"]

kramdown:
  syntax_highlighter_opts:
    disable: true